# Route for generating and saving images
responsive_image_default:
    path:     /%responsive_image.image_directory%/%responsive_image.image_styles_directory%/{stylename}/{filename}
    defaults: { _controller: ResponsiveImageBundle:Image:index }
